### ISSUE TITLE
bugs in chipseq.py & ngstk.py

### ISSUE THREAD

**Issue by mtugrul** [epigen/open_pipelines#1]
Peak calling in open_pipelines/chipseq.py was not working. It turns out that there are a couple of issues to be corrected. Here are my solutions.

1-) In open_pipelines/chipseq.py (line 535), an underscore is missing, i.e.  pipe_manager.wait_for_file... -> pipe_manager._wait_for_file... 
2-) macs2CallPeaks in pypiper/ngstk.py (line 1140) was not functioning properly when it is called in open_pipelines/chipseq.py (line 545). I think this is due to not including "self" in macs2CallPeaks's definition. (this subtle problem is explained here: http://blog.rtwilson.com/got-multiple-values-for-argument-error-with-keyword-arguments-in-python-classes/)). I added a "self" in my local copy.
3-) Also, to be consistent with open_pipelines/chipseq.py, I also changed treatmentBam**s** -> treatmentBam AND controlBam**s** -> controlBam in macs2CallPeaks in pypiper/ngstk.py (line 1140)

With these 3 changes, now open_pipelines/chipseq.py call peaks properly.

**Comment by afrendeiro** [comment]
Hi Murat,
I've fixed these issues and have additionally done a few things as we discussed recently: homogeneized stats reporting between ATAC- and ChIP-seq (including peak number reporting for ChIP); parameterization of bamToBigWig function - you can now control if you want to normalize your tracks or not in the pipeline config.
You can use either branch of pipelines or stick with open_pipelines, master branch. Maybe also make sure you have the latest dev from pypiper and looper <=v0.6-rc1 (the new v0.6-rc2 still has issues when working together with these pipelines).
