### ISSUE TITLE
Fastqc parser bug

### ISSUE THREAD

**Issue by berguner** [epigen/open_pipelines#18]
Hello,

FastQC parsing fails due to "IndexError: list index out of range". Changing the line:
https://github.com/epigen/open_pipelines/blob/d40d700cd108c2882a7dec4764748654651cd5d5/pipelines/atacseq.py#L510
to
`line = [i for i in range(len(content)) if "Sequence length" in content[i]][0]`
fixes the issue. Looks like the last 2 space characters in the search pattern were causing the problem.

Best,
Bekir

**Comment by afrendeiro** [comment]
Thanks. Now fixed in dev
