### ISSUE TITLE
Missing run_spp.R for chipseq.py

### ISSUE THREAD

**Issue by vreuter** [epigen/open_pipelines#5]
I tried subbing in the script from `pipelines/tools` that sounds like it could've been a substitute for the `spp` tool referenced in the pipeline config file's `tools` section, but when I look at the sample's log file, it seems like the command being run would be appropriate for a different script, so it seems like `run_spp.R` and `spp_peak_calling.R` are for different things?

**Comment by afrendeiro** [comment]
They are indeed different (but related) things.

`run_spp.R` is from [here](https://github.com/crazyhottommy/phantompeakqualtools/blob/master/run_spp.R). An ENCODE R library which has some programs which are not really packaged into installable command line tools but exist as a script. `run_spp.R` is (optionally) used by the ATAC/ChIP-seq pipelines to compute the NSC and RSC metrics.

`tools/spp_peak_calling.R` is a script I wrote that uses that `spp` library to call peaks and can be used by the two pipelines above is specified in the config file. I don't usually use `spp` for peak calling though and therefore haven't used that script in a long time.

**Comment by vreuter** [comment]
:+1: thanks @afrendeiro

**Comment by vreuter** [comment]
Cloned the relevant repo and got the script, thanks again!
